# Generated by Django 3.0.4 on 2020-03-19 17:12

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('edwuma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('location', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=50)),
                ('registration_date', models.DateField()),
                ('picture', models.ImageField(max_length=2000, upload_to='')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwuma.Role')),
            ],
        ),
    ]
