# Generated by Django 3.0.4 on 2020-03-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwuma', '0003_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('budget', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
            ],
        ),
    ]
