# Generated by Django 3.0.4 on 2020-03-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edwuma', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=50)),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwuma.SkillCategory')),
            ],
        ),
        migrations.CreateModel(
            name='LoggingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwuma.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwuma.Job')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwuma.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='JobProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_comment', models.TextField(max_length=255)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwuma.Job')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwuma.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwuma.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
                ('payment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwuma.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
                ('payment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwuma.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('date_earned', models.DateField()),
                ('updated_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwuma.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.CharField(max_length=255)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edwuma.Job')),
            ],
        ),
    ]
